CREATE DATABASE 1610013090_VEF2Lok;

USE 1610013090_VEF2Lok;

CREATE TABLE Ritstjori
(
Rit_ID INT AUTO_INCREMENT PRIMARY KEY,
User VARCHAR(20),
Nafn VARCHAR(30),
Pass VARCHAR(20)
);

CREATE TABLE Frettir
(
Frett_ID INT AUTO_INCREMENT PRIMARY KEY,
Rit_ID INT,
Titill VARCHAR(40),
Texti TEXT,
FOREIGN KEY (Rit_ID) REFERENCES Ritstjori(Rit_ID)
);

INSERT INTO Ritstjori(User,Nafn,Pass)
VALUES
('lillibilli','Óskar Agnarsson','1610013090');